### ISSUE TITLE
filtering problem

### ISSUE THREAD

**Issue by cservan** [CanalTP/mimirsbrunn#230]
Hello,
it seems the response filtering by using the keyword "type" does not work. e.g.: 
`http://localhost/autocomplete?q=Paris&type=city`
give as first answer the state_district of Paris, not the city of Paris.

Best.

**Comment by antoine-de** [comment]
It's not really a bug, it's more a bad api problem and a missing feature:

the `type` parameter in the API can filter the main `mimir` types:
* Street
* Address
* Poi
* Stops
* Administrative regions

for historical reason the filter parameter on the administrative regions is `city` (bad design, but at first there were only cities :stuck_out_tongue_winking_eye:  ) thus leading to this misunderstanding.

We can't stop supporting this because of retro-compatibility, but we should add a filter value on `administrative_region` (or maybe `zone` ?) (and remove `city` from the non existent documentation :rofl: ).

We should also add another parameter (`zone_type` ?) to be able to ask only for cities, or countries.

**Comment by jbgriesner** [comment]
@cservan : we are adding the possibility to filter more explicitly the "type of zones" you are looking for as follows : 
* only cities: <bragi IP>/autocomplete?q=Paris&zone_type=city" 
* only cities: <bragi IP>/autocomplete?q=Paris&zone_type=state_district" 

The possible variants for this parameter are : 
* suburb
* city_district                                                                      
* city
* state_district
* state
* country_region
* country
* non_administrative

For more details about the changes just check PR https://github.com/CanalTP/mimirsbrunn/pull/235

**Comment by antoine-de** [comment]
superseeded by #243
