### ISSUE TITLE
Bad results in normal use case (Qwant Maps)

### ISSUE THREAD

**Issue by yhoyhoj** [CanalTP/mimirsbrunn#316]
I'm not sure if this is of interest for you, but I thought it could be useful to have a real example to investigate a possible bug. Feel free to close it if it doesn't belong here.  
I was trying Qwant Maps (which uses Mimir), looking for a real location. The search results were totally useless. On the other hand, results from Openstreetmap Nominatim are spot on.
  
The search query was : "_Rua Antero de Quental coimbra_" (full street name + city name). The city name is the same in Portuguese and English.
Attached are screenshots of the result box for this query on Qwant Maps and OSM.
![Screenshot_2019-06-29 Qwant Maps](https://user-images.githubusercontent.com/2287301/60387527-e0e61580-9aa4-11e9-9006-0477cf6927af.png)
![Screenshot_2019-06-29 OpenStreetMap](https://user-images.githubusercontent.com/2287301/60387529-e3486f80-9aa4-11e9-8860-a1de69f493b4.png)

**Comment by antoine-de** [comment]
It's totally useful to get those kind of examples, thanks a million for the issue!

I'll try to look into it on Monday.

**Comment by amatissart** [comment]
It's probably related to how cities are extracted from OSM data by [cosmogony](https://github.com/osm-without-borders/cosmogony), in order to index each street with its corresponding city name.

In that case the expected city boundary may be https://www.openstreetmap.org/relation/5379538 (admin_level=7), whereas we are currently using [admin_level=8 in Portugal](https://github.com/osm-without-borders/libpostal/blob/84a3bf46e667dbe69aa83ddb3a386127c77dd370/resources/boundaries/osm/pt.yaml#L6)

Would it be correct to consider all boundaries with admin_level=7 in Portugal (Municipalities/Concelho) as cities ?
