### ISSUE TITLE
Discuss if we need a stopOnError flag

### ISSUE THREAD

**Issue by crocme10** [CanalTP/mimirsbrunn#432]
Some import process may generate errors for individual records. Should the whole import stop when this occurs, or should it just raise a warning?

**Comment by crocme10** [comment]
We recently merged a pull request which raises a warning when an import error occurs while doing a bulk operation. It is not clear if the import process should stop rather than just emit a warning. As noted by @amatissart :

> Concernant ton point 2, il faut noter que bulk_index est aussi utilisé par les fonctions index public_index private_index dans le même fichier, qui se chargent de l'indexation ET de la publication (en supprimant aussi l'index précédent). C'est ce qui est utilisé par les importeurs quand ces tâches sont automatisées, et s'il faut une opération humaine pour constater le problème et relancer un import, ça signifie que des données ont été perdues dans l'application entre temps. Dans ce contexte là, passer un stopOnError me paraîtrait effectivement plus sûr.

**Comment by amatissart** [comment]
The range of errors that can be returned for individual records is unclear to me.  
Are they necessarily data errors (due to a malformed input), or could they also be server errors (e.g some ES nodes were temporarily unavailable during the bulk process) ? In the latter case at least, pursing the import would lead to unexpected data loss.

**Comment by amatissart** [comment]
I have run an experiment based on the latest change introduced by #431, with [a custom POIs importer](https://github.com/QwantResearch/fafnir/tree/update-deps) that uses functions from `rubber` to send bulks to Elasticsearch.  

I have used a deliberately high number of threads to overwhelm the ES server.  
Here is the kind of errors I can observe:
```
Nov 02 15:30:06.966 WARN An error occured while importing poi 'osm:node:4744027764': {"type":"es_rejected_execution_exception","reason":"rejected execution of org.elasticsearch.transport.TransportService$4@5eceed8a on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@13b322c0[Running, pool size = 16, active threads = 16, queued tasks = 50, completed tasks = 128017]]","caused_by":null}
```

In this case, the input data is valid but the server cannot process some of the bulk records because of the bulk queue being full.
Previously this kind of error was not handled by rs-es and triggered a panic. With the new implementation the error details are visible but the process is going on, although some of the documents have not been written in the database. As a consequence, the resulted index is incomplete because of these _server_ errors. In most contexts, I don't think this is an acceptable behavior for production pipelines. I would expect the default behavior to be to stop on the first error.

What do you think @crocme10 ?

**Comment by crocme10** [comment]
I agree that the behavior you observe is not adequate, and should that type of error occur, the import process should stop and report an error that should give the person reading that report some clue as to what needs to be done to fix it, if possible.
On the other hand, I would not want the whole process to fail because one record is invalid. The quality of the response to an autocomplete query is not going to be very different for the average user because of that one piece of data missing. So where should we draw the line? I see several routes, that are more or less difficult to implement:
1. the stopOnError solution
2. the 'I try to read the error type (`"type":"es_rejected_execution_exception"`) and decide which cases are acceptable and which are not.
3. the 'I count how many errors i have and if I get more than a configurable threshold, I panic'

There might be more.

**Comment by amatissart** [comment]
The solution 2. seems to be fragile as it would require to have a very fine knowledge of all types of errors that could be returned by Elasticsearch.  

Solutions 1 and 3 can be seen as equivalent if the configurable threshold is the maximum number of errors that should be ignored during the bulk process. The value 0 could be used to stop on the first error.  
That's what I started to implement on this branch: https://github.com/CanalTP/mimirsbrunn/compare/max-bulk-errors
A new field `max_bulk_errors` is defined in `Rubber`, its default value is 0. And it can be set via `.with_max_bulk_errors()` (similarly to `nb_insert_threads`). Of course, the different importers would need to be updated to support this new feature.

Do you think that this approach would fit your needs ? And is this an appropriate API for Rubber ?
